#tomcat
server:
   port: 8888
tomcat:
   uri-encoding: UTF-8


   #mongodb  spring.data.mongodb.uri=mongodb://localhost:27017/springboot-db  没有密码
   #spring.data.mongodb.uri=mongodb://name:pass@localhost:27017/dbname  设置了密码
spring:
  application:
    name: springboot-tjs
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27001/mongodb
      username:
      password:
  #dubbo
  dubbo:
      application:
        name: springboot
      server: true
      registry:
        address: ${zookeeper.address}
      protocol:
        name: dubbo
        port: 12345
      scan: com.springboot.springtest.dubbo.dubboImpl
  #http
  http:
   encoding:
     charset: UTF-8 #HTTP请求和响应的字符集
     enabled: true #是否启用HTTP编码支持
     force: true #是否强制在HTTP请求和响应上对已配置的字符集进行编码
  messages:
    encoding: UTF-8

#   redis:
#      host: ${redis.host}
#      port: ${redis.port}
#      timeout: 3000
#      password: ${redis.password}

  datasource:
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-active: 20
    max-idle: 10
    max-wait: 60000
    connection-timeout: 600000
    min-idle: 1
    validation-query: select 1 from dual
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    filters : stat
    test-on-borrow: true
    test-while-idle: true
  #rabbitmq消息队列
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.springboot.springtest.bean

  aop:
      proxy-target-class: true

#log日志 logback file与path配置一个即可，都配置以file为主
logging:
  path: ${user.dir}/logs/