#tomcat
server:
   port: 8888
tomcat:
   uri-encoding: UTF-8


   #mongodb  spring.data.mongodb.uri=mongodb://localhost:27017/springboot-db  没有密码
   #spring.data.mongodb.uri=mongodb://name:pass@localhost:27017/dbname  设置了密码
spring:
  application:
    name: springboot-tjs
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27001/mongodb
      username:
      password:

#   redis:
#      host: ${redis.host}
#      port: ${redis.port}
#      timeout: 3000
#      password: ${redis.password}

  datasource:
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-active: 20
    max-idle: 10
    max-wait: 60000
    connection-timeout: 600000
    min-idle: 1
    validation-query: select 1 from dual
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    filters : stat
    test-on-borrow: true
    test-while-idle: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.springboot.springtest.bean

  aop:
      proxy-target-class: true