server:
   port: 8888
tomcat:
   uri-encoding: UTF-8

   #mongodb  spring.data.mongodb.uri=mongodb://localhost:27017/springboot-db  没有密码
   #spring.data.mongodb.uri=mongodb://name:pass@localhost:27017/dbname  设置了密码
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27001/mongodb
      username:
      password:

